### ISSUE TITLE
Window service plugin does not work for Wallpaper engine Service.

### ISSUE THREAD

**Issue by PhoenixCODE2322** [Flow-Launcher/Flow.Launcher#1222]
**Describe the bug/issue**
Please look at this, i reported this in PowerToys forum too. https://github.com/microsoft/PowerToys/issues/17231

**To Reproduce**
1. ...search - ws wallpaper Engine
2. ...press enter
3. ...nothing happens

**Screenshots**

**Your System**
```
Windows build number: 21H2, 19044.106
Flow Launcher version: 1.9.3
```
**Flow Launcher Error Log**

[2022-05-25.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8770246/2022-05-25.txt)

i specifically deleted the old log and generated this one after perfoming the bug.

**Comment by jjw24** [comment]
Hey @PhoenixCODE2322 just want to double check since you mentioned PowerToys, are you sure when you are doing this that you are using Flow not PowerToys? (Please share a screenshot after you type in the search)

**Comment by PhoenixCODE2322** [comment]
![image](https://user-images.githubusercontent.com/75798544/170809783-be7d7452-cb25-4378-ae43-9741c0a3158a.png)

My power toys run is disabled, and this issue got solved in power toys after i reported it.

It has to do with wallpaper engine service name containing space in name and using "" to solve it. i think.

**Comment by jjw24** [comment]
PT's plugin is different to ours so that issue still exists for Flow's one right?

**Comment by taooceros** [comment]
@Garulf please take a look.

**Comment by PhoenixCODE2322** [comment]
> PT's plugin is different to ours so that issue still exists for Flow's one right?

Yes

**Comment by Garulf** [comment]
Sorry been busy lately. I did already take a look at the thread posted above and will look into fixing the issue as soon as I can.

**Comment by Garulf** [comment]
I have taken a few solid swings at this and have failed miserably sadly. Despite my attempts Powershell will not escape the quotes sent by the plugin. I'll have to loop back to this when I can.
