### ISSUE TITLE
Combine/remove duplicate entries

### ISSUE THREAD

**Issue by skjerns** [Flow-Launcher/Flow.Launcher#307]
It happens quite often that Flow shows me duplicate applications. Would it be possible to check whether something is already in the index and keep the program index cleaner? This could also be done e.g. by checking the link target instead of the link location (including args of course).

Related: #303 

![image](https://user-images.githubusercontent.com/14980558/105322374-168fa980-5bc9-11eb-8d9d-b74ed9f8898c.png)

**Comment by taooceros** [comment]
This is on progress. Check out #78.

**Comment by skjerns** [comment]
great! thanks!

**Comment by taooceros** [comment]
No need to close, will close when that pr has merged. Thank you for pointing out the need!

**Comment by jjw24** [comment]
@skjerns This issue should be fixed, but 1.8.0 may not get released for a while, you can download the build here to use it https://ci.appveyor.com/api/buildjobs/8k1g0edbeqxlbqwk/artifacts/Output%2FPackages%2FFlow-Launcher-v1.7.1.exe

**Comment by skjerns** [comment]
thanks! I'll try it out!

**Comment by skjerns** [comment]
What is still missing is automatic indexing of `C:\ProgramData\Microsoft\Windows\Start Menu` - could that be added? Quite a few programs are using this as the default

**Comment by taooceros** [comment]
Weird I remember that's included. Have you selected the option to index start menu?

**Comment by skjerns** [comment]
I just saw: It is included, however, there is a program missing that should be there: `NeuroBS Presentation`

![image](https://user-images.githubusercontent.com/14980558/107943861-953ff280-6f8d-11eb-94e1-28d89de2a708.png)

It is showing up in the start menu, but not in wox

![image](https://user-images.githubusercontent.com/14980558/107943935-adb00d00-6f8d-11eb-8f4d-fd3e631a1c3f.png)

**Comment by taooceros** [comment]
> I just saw: It is included, however, there is a program missing that should be there: `NeuroBS Presentation`
> 
> ![image](https://user-images.githubusercontent.com/14980558/107943861-953ff280-6f8d-11eb-94e1-28d89de2a708.png)
> 
> It is showing up in the start menu, but not in wox
> 
> ![image](https://user-images.githubusercontent.com/14980558/107943935-adb00d00-6f8d-11eb-8f4d-fd3e631a1c3f.png)
> 
> these are my settings:
> 
> ![image](https://user-images.githubusercontent.com/14980558/107943974-be608300-6f8d-11eb-9cf4-815d55d99e00.png)
> 

I will take a look soon. AFKing now. Maybe there are multiple lnk pointing to the same exe but both of them doesn't contain descriptions so none of them are kept.
This may be a logic issue on hashing.
Thank you for pointing that out!

**Comment by skjerns** [comment]
thanks! by the way, this is the link

![image](https://user-images.githubusercontent.com/14980558/107966041-9aac3580-6fab-11eb-989f-4a7b3c4532e6.png)

However, there is something strange on the second tab:

![image](https://user-images.githubusercontent.com/14980558/107966128-b4e61380-6fab-11eb-9c3c-0e466e5912b5.png)

**Comment by taooceros** [comment]
> thanks! by the way, this is the link
> 
> ![image](https://user-images.githubusercontent.com/14980558/107966041-9aac3580-6fab-11eb-989f-4a7b3c4532e6.png)
> 
> However, there is something strange on the second tab:
> 
> ![image](https://user-images.githubusercontent.com/14980558/107966128-b4e61380-6fab-11eb-9c3c-0e466e5912b5.png)
> 
> this is the content of the `lnk` which looks quite different from others I examinde
> 
> ```
> L   ���     �      F�P                                  �   �               ��� �P�O� �:i���� +00�� /C:\                   V 1     mQ
> L� Windows @ 	 � ﾇOwHzQ b.   ��    �               �
> �W i n d o w s   � \ 1     zQ#b� Installer D 	 � ﾇO�IzQ#b.   ��    �               ��� I n s t a l l e r   � � 1     zQ#b� {A43A9~1  ~ 	 � �zQ#bzQ#b.   V�    0               d�� { A 4 3 A 9 8 5 1 - 8 7 7 0 - 4 1 3 5 - B 4 6 9 - E A 7 7 C 0 2 E 3 8 F F }   � n 2  h  zQ#b! ICON1D~2.EXE  R 	 � �zQ#bzQ#b.   ���   �               ��� I c o n 1 D 3 9 4 6 A 1 . e x e   �   R . . \ . . \ . . \ W i n d o w s \ I n s t a l l e r \ { A 4 3 A 9 8 5 1 - 8 7 7 0 - 4 1 3 5 - B 4 6 9 - E A 7 7 C 0 2 E 3 8 F F } \ I c o n 1 D 3 9 4 6 A 1 . e x e � � L C : \ W i n d o w s \ I n s t a l l e r \ { A 4 3 A 9 8 5 1 - 8 7 7 0 - 4 1 3 5 - B 4 6 9 - E A 7 7 C 0 2 E 3 8 F F } \ I c o n 1 D 3 9 4 6 A 1 . e x e ��  �  �FtVk]AMMz8SvzUNO`B%{>EQ=o1zSsp9ZlEKlJ[EbE                                                                                                                                                                                                                           F t V k ] A M M z 8 S v z U N O ` B % { > E Q = o 1 z S s p 9 Z l E K l J [ E b E                                                                                                                                                                                                                                                                                                                                                                                                                                                       ��  �  �%SystemRoot%\Installer\{A43A9851-8770-4135-B469-EA77C02E38FF}\Icon1D3946A1.exe                                                                                                                                                                                      % S y s t e m R o o t % \ I n s t a l l e r \ { A 4 3 A 9 8 5 1 - 8 7 7 0 - 4 1 3 5 - B 4 6 9 - E A 7 7 C 0 2 E 3 8 F F } \ I c o n 1 D 3 9 4 6 A 1 . e x e                                                                                                                                                                                                                                                                                                                                                                                 
> ```

emmm that's werid. I think this will be stored as log, so would you please share the log with me so that I can check whether it is problem when loading the lnkprogram?

**Comment by skjerns** [comment]
Logfile reports the following

```
2021-02-15 18:01:03.6254|ERROR||------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
2021-02-15 18:01:03.6318|ERROR||
Exception full name: System.Runtime.InteropServices.COMException
Error status: KNOWN
Class name: Win32
Calling method: LnkProgram
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Windows Media Player.lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
2021-02-15 18:01:03.6318|ERROR||------------- END Flow.Launcher.Plugin.Program exception -------------
2021-02-15 18:01:03.6318|ERROR||------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
2021-02-15 18:01:03.6495|ERROR||
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Windows\SystemApps\Microsoft.Windows.SecHealthUI_cw5n1h2txyewy
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: Microsoft.Windows.SecHealthUI_cw5n1h2txyewy!SecHealthUI can't find logo uri for Assets\Square44x44Logo.png in package location: C:\Windows\SystemApps\Microsoft.Windows.SecHealthUI_cw5n1h2txyewy
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
2021-02-15 18:01:03.6495|ERROR||------------- END Flow.Launcher.Plugin.Program exception -------------
2021-02-15 18:01:03.6495|ERROR||------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
2021-02-15 18:01:03.6662|ERROR||
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Program Files\WindowsApps\word.office.com-CECA1A7F_1.0.0.0_neutral__jc2kecmnkxwqc
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: word.office.com-CECA1A7F_jc2kecmnkxwqc!App can't find logo uri for Images\Square44x44Logo.png in package location: C:\Program Files\WindowsApps\word.office.com-CECA1A7F_1.0.0.0_neutral__jc2kecmnkxwqc
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
2021-02-15 18:01:03.6662|ERROR||------------- END Flow.Launcher.Plugin.Program exception -------------
2021-02-15 18:01:03.6772|ERROR||------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
2021-02-15 18:01:03.6772|ERROR||
Exception full name: System.Runtime.InteropServices.COMException
Error status: KNOWN
Class name: Win32
Calling method: LnkProgram
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\ODBC Data Sources (32-bit).lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
2021-02-15 18:01:03.6772|ERROR||------------- END Flow.Launcher.Plugin.Program exception -------------
2021-02-15 18:01:04.5258|ERROR||------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
2021-02-15 18:01:04.5258|ERROR||
Exception full name: System.Runtime.InteropServices.COMException
Error status: KNOWN
Class name: Win32
Calling method: LnkProgram
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Windows Media Player.lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
2021-02-15 18:01:04.5379|ERROR||------------- END Flow.Launcher.Plugin.Program exception -------------
2021-02-15 18:01:04.5379|ERROR||------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
2021-02-15 18:01:04.5568|ERROR||
Exception full name: System.Runtime.InteropServices.COMException
Error status: KNOWN
Class name: Win32
Calling method: LnkProgram
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\ODBC Data Sources (32-bit).lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
2021-02-15 18:01:04.5568|ERROR||------------- END Flow.Launcher.Plugin.Program exception -------------

```

**Comment by taooceros** [comment]
ok, so it is not because of lnkprogram issue, check out this build. https://ci.appveyor.com/api/buildjobs/6sx2mp18s8lwkca7/artifacts/Output%2FPackages%2FFlow-Launcher-v1.7.1.exe

**Comment by skjerns** [comment]
![image](https://user-images.githubusercontent.com/14980558/107982569-92acbf80-6fc4-11eb-9535-33842f83484e.png)

now the help gets shown, but the main program not haha

**Comment by skjerns** [comment]
```
2021-02-15 19:33:42.6716|ERROR||------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
2021-02-15 19:33:42.6793|ERROR||
Exception full name: System.Runtime.InteropServices.COMException
Error status: KNOWN
Class name: Win32
Calling method: LnkProgram
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Windows Media Player.lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
2021-02-15 19:33:42.6793|ERROR||------------- END Flow.Launcher.Plugin.Program exception -------------
2021-02-15 19:33:42.7003|ERROR||------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
2021-02-15 19:33:42.7003|ERROR||
Exception full name: System.Runtime.InteropServices.COMException
Error status: KNOWN
Class name: Win32
Calling method: LnkProgram
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\ODBC Data Sources (32-bit).lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
2021-02-15 19:33:42.7141|ERROR||------------- END Flow.Launcher.Plugin.Program exception -------------
2021-02-15 19:33:42.7346|ERROR||------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
2021-02-15 19:33:42.7410|ERROR||
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Windows\SystemApps\Microsoft.Windows.SecHealthUI_cw5n1h2txyewy
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: Microsoft.Windows.SecHealthUI_cw5n1h2txyewy!SecHealthUI can't find logo uri for Assets\Square44x44Logo.png in package location: C:\Windows\SystemApps\Microsoft.Windows.SecHealthUI_cw5n1h2txyewy
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
2021-02-15 19:33:42.7410|ERROR||------------- END Flow.Launcher.Plugin.Program exception -------------
2021-02-15 19:33:43.4219|ERROR||------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
2021-02-15 19:33:43.4290|ERROR||
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Program Files\WindowsApps\word.office.com-CECA1A7F_1.0.0.0_neutral__jc2kecmnkxwqc
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: word.office.com-CECA1A7F_jc2kecmnkxwqc!App can't find logo uri for Images\Square44x44Logo.png in package location: C:\Program Files\WindowsApps\word.office.com-CECA1A7F_1.0.0.0_neutral__jc2kecmnkxwqc
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
2021-02-15 19:33:43.4290|ERROR||------------- END Flow.Launcher.Plugin.Program exception -------------
2021-02-15 19:33:43.6611|ERROR||------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
2021-02-15 19:33:43.6675|ERROR||
Exception full name: System.Runtime.InteropServices.COMException
Error status: KNOWN
Class name: Win32
Calling method: LnkProgram
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Windows Media Player.lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
2021-02-15 19:33:43.6675|ERROR||------------- END Flow.Launcher.Plugin.Program exception -------------
2021-02-15 19:33:43.6866|ERROR||------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
2021-02-15 19:33:43.6866|ERROR||
Exception full name: System.Runtime.InteropServices.COMException
Error status: KNOWN
Class name: Win32
Calling method: LnkProgram
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\ODBC Data Sources (32-bit).lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
2021-02-15 19:33:43.6987|ERROR||------------- END Flow.Launcher.Plugin.Program exception -------------

```

**Comment by taooceros** [comment]
The logs is fine. These errors are normal. Would you please show me with the target program of these lnk?

**Comment by skjerns** [comment]
it's NeuroBS Presentation player, you can download the installer here:

https://www.neurobs.com/menu_presentation/menu_download/process_download?user_id=10&version=22.1&build=01.21.21&bit=1&player=0

**Comment by taooceros** [comment]
@skjerns I found the issue. Both of them resolve to the same path, so that only one of them are kept.

**Comment by taooceros** [comment]
![image](https://user-images.githubusercontent.com/45326534/108031440-b3d1d800-6fe5-11eb-8837-ec4e0f885904.png)
my antivirus program actually block it, suggesting that it contains trojan.....Not sure why.

**Comment by skjerns** [comment]
I'm pretty sure there is no virus inside, it's a product that costs several thousand dollars. `HEUR` means the heuristic rules determined that it was maybe containing malicious code, this could be due to anything, e.g. code that makes the taskbar dissappear, etc. Usually the heuristics have a lot of false positives compared to hash methods

**Comment by taooceros** [comment]
Oh haha understand. No problem for that. I am not sure how we should resolve this issue. Maybe we should make the list we registered manually outside the one that will be checked for duplicate.
Let me take a try, and I will reach out back.

**Comment by taooceros** [comment]
@skjerns https://ci.appveyor.com/api/buildjobs/60w6675kijv0378n/artifacts/Output%2FPackages%2FFlow-Launcher-v1.7.1.exe
check out this build, and manually add the folder containing the Presentation program to the program source.
This may create an extra duplicate that kept by autoindexing, maybe I can add a distinct to that to check whether it works.

**Comment by taooceros** [comment]
@skjerns sorry for re-asking to try so frequently XD, I just implement the thing I describe on the last comment. It works, and only one result will be stored.

**Comment by taooceros** [comment]
Here is the artifact @skjerns https://ci.appveyor.com/api/buildjobs/mi155t89nran6cwn/artifacts/Output%2FPackages%2FFlow-Launcher-v1.7.1.exe

**Comment by jjw24** [comment]
> @skjerns I found the issue. Both of them resolve to the same path, so that only one of them are kept.

Could the documentation use an argument to pass through a parameter to the executable to bring up help? Surely both entries can't be running the program

**Comment by taooceros** [comment]
> > @skjerns I found the issue. Both of them resolve to the same path, so that only one of them are kept.
> 
> Could the documentation use an argument that's passed through as a parameter to the executable to bring up help? Surely both entries can't be running the program

I don't know how this programs works. but seems not quite possible

**Comment by jjw24** [comment]
If you look at the property of the shortcut, does it show any arguments being passed through to the executable?

**Comment by taooceros** [comment]
![image](https://user-images.githubusercontent.com/45326534/108037872-05cb2b80-6fef-11eb-9e93-6b3a1ea632ca.png)
No, I don't understand how this works.

**Comment by skjerns** [comment]
I think this is a different style lnk created by windows installer, might be connected to App Store stuff.

see also the source code of the lnk, maybe that helps?
```
L   ���     �      F�P                                  �   �               ��� �P�O� �:i���� +00�� /C:\                   V 1     mQ
L� Windows @ 	 � ﾇOwHzQ b.   ��    �               �
�W i n d o w s   � \ 1     zQ#b� Installer D 	 � ﾇO�IzQ#b.   ��    �               ��� I n s t a l l e r   � � 1     zQ#b� {A43A9~1  ~ 	 � �zQ#bzQ#b.   V�    0               d�� { A 4 3 A 9 8 5 1 - 8 7 7 0 - 4 1 3 5 - B 4 6 9 - E A 7 7 C 0 2 E 3 8 F F }   � n 2  h  zQ#b! ICON1D~2.EXE  R 	 � �zQ#bzQ#b.   ���   �               ��� I c o n 1 D 3 9 4 6 A 1 . e x e   �   R . . \ . . \ . . \ W i n d o w s \ I n s t a l l e r \ { A 4 3 A 9 8 5 1 - 8 7 7 0 - 4 1 3 5 - B 4 6 9 - E A 7 7 C 0 2 E 3 8 F F } \ I c o n 1 D 3 9 4 6 A 1 . e x e � � L C : \ W i n d o w s \ I n s t a l l e r \ { A 4 3 A 9 8 5 1 - 8 7 7 0 - 4 1 3 5 - B 4 6 9 - E A 7 7 C 0 2 E 3 8 F F } \ I c o n 1 D 3 9 4 6 A 1 . e x e ��  �  �FtVk]AMMz8SvzUNO`B%{>EQ=o1zSsp9ZlEKlJ[EbE                                                                                                                                                                                                                           F t V k ] A M M z 8 S v z U N O ` B % { > E Q = o 1 z S s p 9 Z l E K l J [ E b E                                                                                                                                                                                                                                                                                                                                                                                                                                                       ��  �  �%SystemRoot%\Installer\{A43A9851-8770-4135-B469-EA77C02E38FF}\Icon1D3946A1.exe                                                                                                                                                                                      % S y s t e m R o o t % \ I n s t a l l e r \ { A 4 3 A 9 8 5 1 - 8 7 7 0 - 4 1 3 5 - B 4 6 9 - E A 7 7 C 0 2 E 3 8 F F } \ I c o n 1 D 3 9 4 6 A 1 . e x e                                                                                                                                                                                                                                                                                                                                                                                 
```

**Comment by taooceros** [comment]
> I think this is a different style lnk created by windows installer, might be connected to App Store stuff.
> 
> see also the source code of the lnk, maybe that helps?
> 
> ```
> L   ���     �      F�P                                  �   �               ��� �P�O� �:i���� +00�� /C:\                   V 1     mQ
> L� Windows @ 	 � ﾇOwHzQ b.   ��    �               �
> �W i n d o w s   � \ 1     zQ#b� Installer D 	 � ﾇO�IzQ#b.   ��    �               ��� I n s t a l l e r   � � 1     zQ#b� {A43A9~1  ~ 	 � �zQ#bzQ#b.   V�    0               d�� { A 4 3 A 9 8 5 1 - 8 7 7 0 - 4 1 3 5 - B 4 6 9 - E A 7 7 C 0 2 E 3 8 F F }   � n 2  h  zQ#b! ICON1D~2.EXE  R 	 � �zQ#bzQ#b.   ���   �               ��� I c o n 1 D 3 9 4 6 A 1 . e x e   �   R . . \ . . \ . . \ W i n d o w s \ I n s t a l l e r \ { A 4 3 A 9 8 5 1 - 8 7 7 0 - 4 1 3 5 - B 4 6 9 - E A 7 7 C 0 2 E 3 8 F F } \ I c o n 1 D 3 9 4 6 A 1 . e x e � � L C : \ W i n d o w s \ I n s t a l l e r \ { A 4 3 A 9 8 5 1 - 8 7 7 0 - 4 1 3 5 - B 4 6 9 - E A 7 7 C 0 2 E 3 8 F F } \ I c o n 1 D 3 9 4 6 A 1 . e x e ��  �  �FtVk]AMMz8SvzUNO`B%{>EQ=o1zSsp9ZlEKlJ[EbE                                                                                                                                                                                                                           F t V k ] A M M z 8 S v z U N O ` B % { > E Q = o 1 z S s p 9 Z l E K l J [ E b E                                                                                                                                                                                                                                                                                                                                                                                                                                                       ��  �  �%SystemRoot%\Installer\{A43A9851-8770-4135-B469-EA77C02E38FF}\Icon1D3946A1.exe                                                                                                                                                                                      % S y s t e m R o o t % \ I n s t a l l e r \ { A 4 3 A 9 8 5 1 - 8 7 7 0 - 4 1 3 5 - B 4 6 9 - E A 7 7 C 0 2 E 3 8 F F } \ I c o n 1 D 3 9 4 6 A 1 . e x e                                                                                                                                                                                                                                                                                                                                                                                 
> ```
> 
> the link target is this
> 
> ![image](https://user-images.githubusercontent.com/14980558/108045478-cb3fae00-7043-11eb-8648-da993e6581e9.png)

Yeah the issue is that all the link points to the same program, so the hasher will view them as one.
Therefore, I think we can only do that by manually adding it to index as I suggest before.

**Comment by skjerns** [comment]
however, how does windows figure out which program to run? It can't be entirely the same program

also the icon is different, so that might be used as a distinguishing feature?
