### ISSUE TITLE
BUG: Explorer Plugin: Path Search Action Keyword does not work

### ISSUE THREAD

**Issue by daninedan** [Flow-Launcher/Flow.Launcher#3416]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I am using the latest version of Flow Launcher.

### Problem Description

Path Search Action Keyword does not work. Using it does not produce any results although folders are found when using the Search Action Keyword.

### To Reproduce

1. Define a Path Search Action Keyword
2. Use it searching for a folder
3. No folders are displayed

### Screenshots

![Image](https://github.com/user-attachments/assets/dd128877-3db2-4635-82a3-785100096f58)

![Image](https://github.com/user-attachments/assets/38ce27fa-30fa-4a98-86e6-f3cfebddf87a)

![Image](https://github.com/user-attachments/assets/43de4800-13ec-4876-8ef1-0a67a88b323c)

### Flow Launcher Version

1.19.5

### Windows Build Number

10.0.26100.3476

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by TechySC23** [comment]
@daninedan While I am not a developer of Flow launcher, I do understand that file content search is for "Files" and not "Folders", that means, it will work for files **only** not folders. The purpose is for "content" of the file, like a txt file.

One more thing, File Content Search works with the Everything Application installed with the file content indexing enabled.

**Comment by jjw24** [comment]
If I remember correctly, path search is for searching a path e.g `c:\blah` and we haven't implemented actual folder search (which we should).

**Comment by d-duesentrip** [comment]
Hi everyone. Thank you very much for your comments. I think my description was wrong but the bug still exists. The path keyword does not work in general. Not even for a path search. It seems it is restricted to search only in the Quick access elements?

**Comment by 01Dri** [comment]
The bug occurs in the search manager. I'm working on a fix.

**Comment by jjw24** [comment]
@01Dri I think this is also fixed in your recent PR, I was able to navigate path using the action keyword during testing. Could you double check the dev build please.

**Comment by 01Dri** [comment]
@jjw24 The problem is still happening.

<img width="1093" height="81" alt="Image" src="https://github.com/user-attachments/assets/8eacbbee-ba0b-423f-a99e-21bb5a3a20a7" />

I have a question... When using the path search action, should it return only folders? I just want to understand the idea behind this feature.

**Comment by jjw24** [comment]
It's actually designed to be used to search for path only like c:\blah but not blah. So it should follow the same principle of a path search 

I think we should add new folder or file only search options so for example you can type 'blah' and get the blah directory only or blah_file for file only.

**Comment by 01Dri** [comment]
> It's actually designed to be used to search for path only like c:\blah but not blah. So it should follow the same principle of a path search 

 Hmm, I understand now. So both using only C:\ in Flow or fo (action keyword) C:\  should return the same results, right? If that’s correct, then the feature is working as expected.. but I think it could be a bit confusing for users

> I think we should add new folder or file only search options so for example you can type 'blah' and get the blah directory only or blah_file for file only.

I agree. I can help with implementing these new features.

**Comment by jjw24** [comment]
>I think we should add new folder or file only search options so for example you can type 'blah' and get the blah directory only or blah_file for file only.

>I agree. I can help with implementing these new features.

That would be great. This will require working with windows search queries which you should already see similar queries in the current code as a reference.

**Comment by jjw24** [comment]
I will close this this issue for now since path action keyword is properly traversing paths.
