### ISSUE TITLE
Hitting Tab for Autocompletion doesn't work properly when Last Query Style is changed

### ISSUE THREAD

**Issue by HGhostRevisionist88** [Flow-Launcher/Flow.Launcher#971]
When Last Query Style is changed to **Empty Last Query**, it affects the way when tab autocompletion works. it does it by leaing the type cursor at the beginning instead of putting it at the end to keep typing something needed for a command to work, I thought maybe it was just the way it worked but I saw the videos #850 and then I made a test and used default settings and disable and changed and enable things until I finally found what broke the way autocompletion works, I wasn't using autocompletion until I installed today Plugin Runner and then I saw the problem when I wanted to type the arguments needed for nircmd to do something.
Not a dealbreaker but I better changed the setting back to Select Last Query so it will be easier to do stuff.

Preserve Last Query seems to work properly as well, so it seems it is just Empty Last Query and the one I liked the one causing conflicts with it.

1. Open Settings and change Last Query Style to Empty Last Query
2. Restart Flow
3. Open Flow and type anything, then hit tab and you will see the cursor at the beginning instead of the end like it should be.

Windows build number: 10.0.19043.1415
Flow Launcher version: 1.9.1

**Comment by taooceros** [comment]
Theoretically it should be fixed in 1.9.1. Could you take a try on the latest dev version? https://ci.appveyor.com/api/buildjobs/qfnsboo6kyge7wk5/artifacts/Output%2FPackages%2FFlow-Launcher-Setup.exe

**Comment by HGhostRevisionist88** [comment]
Tested it and the issue still happens when Flow gets restarted.

**Comment by Garulf** [comment]
I was able to reproduce the error, I'll start taking a look along with @taooceros
